definitions:
  namespace:
    contenteximdemo:
      uri: http://www.onehippo.org/contenteximdemo/nt/1.0
      cnd: namespaces/content-exim-demo.cnd
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
    /hippo:configuration/hippo:groups/author:
      hipposys:members:
        operation: add
        type: string
        value: [author]
    /hippo:configuration/hippo:groups/editor:
      hipposys:members:
        operation: add
        type: string
        value: [editor]
    /hippo:configuration/hippo:groups/webmaster:
      hipposys:members:
        operation: add
        type: string
        value: [editor]
    /hippo:configuration/hippo:domains/hippofolders/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [sitewriters]
    /hippo:configuration/hippo:domains/preview-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [previewusers]
    /hippo:configuration/hippo:domains/live-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [liveusers]
