definitions:
  config:
    /hst:hst/hst:configurations/contenteximdemo/hst:pages/faqlist:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: faqlist/main
