definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-blogauthor-folder:
      jcr:primaryType: hippostd:templatequery
      jcr:mixinTypes: ['hipposys:implementation']
      hippostd:icon: addfolder_ico
      hippostd:modify: [./_name, $name, './hippotranslation:id', $uuid, './hippotranslation:locale',
        $inherited]
      hipposys:classname: org.hippoecm.repository.impl.query.DirectPath
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-blogauthor-folder/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /hippostd:folder:
          jcr:primaryType: hippostd:folder
          jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
          jcr:uuid: 026f72f1-5ba4-4ebc-9918-48c2588de64e
          hippostd:foldertype: [new-blogauthor-document, new-blogauthor-folder]
          hippotranslation:id: generated id
          hippotranslation:locale: inherited locale
